export type Token = {
    kind: TokenType;
    value: string | number | boolean | null;
};

export enum TokenType {
    // Simple tokens
    BANG = "BANG",
    BANG_EQUAL = "BANG_EQUAL",
    EQUAL = "EQUAL",
    EQUAL_EQUAL = "EQUAL_EQUAL",
    GT = "GT",
    GTE = "GTE",
    LT = "LT",
    LTE = "LTE",
    MINUS = "MINUS",
    PLUS = "PLUS",
    MULT = "MULT",
    DIV = "DIV",
    MOD = "MOD",
    OPENPAREN = "OPENPAREN",
    CLOSEPAREN = "CLOSEPAREN",
    OPENBRACKET = "OPENBRACKET",
    CLOSEBRACKET = "CLOSEBRACKET",
    SEMICOLON = "SEMICOLON",
    HASH = "HASH",
    QUOTES = "QUOTES",
    COMMA = "COMMA",
    // Keywords
    FN = "FN",
    IF = "IF",
    ELSE = "ELSE",
    WHILE = "WHILE",
    FOR = "FOR",
    INIT = "INIT",
    PRINT = "PRINT",
    AND = "AND",
    OR = "OR",
    // Identifiers and literals
    IDENTIFIER = "IDENTIFIER",
    NUMBER = "NUMBER",
    STRING = "STRING",
    BOOLEAN = "BOOLEAN",
    NIL = "NIL",
    EOF = "EOF",
};

export const symbols: Partial<Record<TokenType, string>> = {
    [TokenType.BANG]: "!",
    [TokenType.BANG_EQUAL]: "!=",
    [TokenType.EQUAL]: "=",
    [TokenType.EQUAL_EQUAL]: "==",
    [TokenType.GT]: ">",
    [TokenType.GTE]: ">=",
    [TokenType.LT]: "<",
    [TokenType.LTE]: "<=",
    [TokenType.SEMICOLON]: ";",
    [TokenType.MINUS]: "-",
    [TokenType.PLUS]: "+",
    [TokenType.MULT]: "*",
    [TokenType.DIV]: "/",
    [TokenType.MOD]: "%",
    [TokenType.OPENPAREN]: "(",
    [TokenType.CLOSEPAREN]: ")",
    [TokenType.OPENBRACKET]: "{",
    [TokenType.CLOSEBRACKET]: "}",
    [TokenType.HASH]: "#",
    [TokenType.COMMA]: ",",
    [TokenType.EOF]: "EOF",
    [TokenType.PRINT]: "PRINT",
    [TokenType.INIT]: "INIT",
    [TokenType.AND]: "and",
    [TokenType.OR]: "or",
    [TokenType.FN]: "FN",
    [TokenType.IF]: "IF",
    [TokenType.ELSE]: "ELSE",
    [TokenType.WHILE]: "WHILE",
    [TokenType.FOR]: "FOR",
    [TokenType.QUOTES]: "\""
};